download.file(url = "https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip", destfile = "household_power_consumption.zip")
unzip("household_power_consumption.zip")
raw_data<-read.csv("household_power_consumption.txt", sep=";", header = TRUE)
data_to_plot <-raw_data[raw_data$Date %in% c("1/2/2007","2/2/2007") ,]
times <- strptime(paste(data_to_plot$Date, data_to_plot$Time, sep=" "), "%d/%m/%Y %H:%M:%S") 
png("plot4.png", width=480, height=480)
par(mfrow = c(2, 2)) 
plot(times, as.numeric(data_to_plot$Global_active_power), type="l", xlab="", ylab="Global Active Power", cex=0.2)
plot(times, as.numeric(data_to_plot$Voltage), type="l", xlab="datetime", ylab="Voltage")
plot(times, as.numeric(data_to_plot$Sub_metering_1), type="l", ylab="Energy Submetering", xlab="")
lines(times, as.numeric(data_to_plot$Sub_metering_2), type="l", col="red")
lines(times, as.numeric(data_to_plot$Sub_metering_3), type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=, lwd=2.5, col=c("black", "red", "blue"), bty="o")
plot(times, as.numeric(data_to_plot$Global_reactive_power), type="l", xlab="datetime", ylab="Global_reactive_power")
dev.off()
